### ISSUE TITLE
I can't import compedium items

### ISSUE THREAD

**Issue by wagnerlague** [foundryvtt-starfinder/foundryvtt-starfinder#1020]
**Describe the bug**
I can't import compedium items

**To Reproduce**

Foudnry Version V10 291
Starfinder module version 0.23.0

When trying to import a compendium only the folder is imported and the items are not.
The error it shows is the following

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Preprocessor.advance (/home/ubuntu/foundry/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:137:35)
    at Tokenizer._consume (/home/ubuntu/foundry/resources/app/node_modules/parse5/dist/tokenizer/index.js:271:34)
    at Tokenizer._runParsingLoop (/home/ubuntu/foundry/resources/app/node_modules/parse5/dist/tokenizer/index.js:222:29)
    at Tokenizer.write (/home/ubuntu/foundry/resources/app/node_modules/parse5/dist/tokenizer/index.js:249:14)
    at parseFragment (/home/ubuntu/foundry/resources/app/node_modules/parse5/dist/index.js:41:22)
    at cleanHTML (/home/ubuntu/foundry/resources/app/dist/database/validators.mjs:1:180)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/ubuntu/foundry/resources/app/dist/database/sanitization.mjs:1:1408)
    at Function._sanitizeFields (/home/ubuntu/foundry/resources/app/dist/database/backend/server-document.mjs:1:2099)
    at Function._sanitizeFields (/home/ubuntu/foundry/resources/app/dist/database/backend/server-document.mjs:1:2326)
    at Function.sanitizeUserInput (/home/ubuntu/foundry/resources/app/dist/database/backend/server-document.mjs:1:1802)

**Comment by Iankid** [comment]
Those errors seem to be associated with the Tokenizer module. Which I can't think of why it would be related.
But also, are you attempting to import the entire compendium?! That is an insane amount of data, and you should only be importing single items as needed.

**Comment by wagnerlague** [comment]
> Esses erros parecem estar associados ao módulo Tokenizer. O que não consigo pensar em por que estaria relacionado. Mas também, você está tentando importar o compêndio inteiro?! Essa é uma quantidade insana de dados e você só deve importar itens individuais conforme necessário.

I suspected another module was causing the conflict and disabled all modules. I tested and the error persists.
And the error happens if I try to import just one item or all, regardless of quantity.

**Comment by Iankid** [comment]
Can you try adding an item to a character sheet from the compendium?

**Comment by wagnerlague** [comment]
I just updated all my modules, did a new test, the error keeps happening.
The system is up to date and all modules are up to date, but all are inactive.
I still can't import from the compendiums

> Você pode tentar adicionar um item a uma ficha de personagem do compêndio?



> Você pode tentar adicionar um item a uma ficha de personagem do compêndio?

I am logged in as master.
step 1
open the compendium
step 2
I go to Item, select a folder, for example classes

step 3
right-click on the mechanic class
and choose to import item

the error happens

**Comment by wagnerlague** [comment]
> 


> Você pode tentar adicionar um item a uma ficha de personagem do compêndio?

The same error happens if I log in as a master, select the mechanic class in the compendium and try to drag it into the character sheet without importing it first

**Comment by Iankid** [comment]
I believe right clicking to import tries to do the whole compendium. Try a simple drag n drop

**Comment by LebombJames** [comment]
This is an issue with core foundry. Completely uninstall the software, then reinstall it. Ensure you have no automatic backup software syncing your Foundry data or installation folder.

**Comment by wagnerlague** [comment]
> This is an issue with core foundry. Completely uninstall the software, then reinstall it. Ensure you have no automatic backup software syncing your Foundry data or installation folder.

I installed Foundry version 10 291, updated all modules and systems and now it's working again.
thanks for the support.
