### ISSUE TITLE
Unable to drop JournalPage on Actor

### ISSUE THREAD

**Issue by paulyhedral** [foundryvtt-starfinder/foundryvtt-starfinder#1394]
**Is your feature request related to a problem? Please describe.**
I am working on a Foundry module that supports creating parcels of items that can be given to a PC by dropping the parcel onto the actor sheet. The parcel is implemented using JournalEntry and JournalEntryPage, and relies on the dropActorSheetData hook to fire in order to copy the items to the PC. However, this system only seems to support dropping Items on the actor.

**Describe the solution you'd like**
Can you add support for additional types to be dropped on the actor?

**Additional context**
The following error is seen in the console log when dropping `JournalPage`s on the actor:
```
Uncaught (in promise) Error: Invalid Document type 'undefined' provided to Item.fromDropData.
    at Item.fromDropData (foundry.js:11496:15)
    at async ActorSheetSFRPGCharacter.processDroppedData (base.js:1164:28)
 fromDropData @ foundry.js:11496
```

**Comment by levirak** [comment]
Can you please enumerate some objects you're interested in and what you'd like done with them? It sounds like you're at least interested in `JournalEntry` and `JournalEntryPage`. The only thing I can think to do with those is to promote the actor's player to a limited owner of the entry/page.

**Comment by paulyhedral** [comment]
Yes, I need `JournalEntry` and `JournalEntryPage`. The module expects to receive an event callback when one of those types is dropped on the actor.

The hook in question is `dropActorSheetData`: https://github.com/sweetrpg/lootparcels-foundryvtt/blob/feature/83-sfrpg/loot-parcels.js#L163

```
Hooks.on('dropActorSheetData', async (actor, html, item) => {
```

**Comment by levirak** [comment]
Gotcha. So the only thing you need is for sfrpg's hook to silently ignore dropped data that isn't an item.

**Comment by levirak** [comment]
I double-checked with sweetrpg/lootparcels-foundryvtt#83, and it looks like this issue is not yet resolved. Digging in a bit deeper, it looks like the root problem is that SFRPG needs to manually call the `"dropActorSheetData"` hook. I mistakenly believed that that was happening implicitly. The implementation of Foundry's `ActorSheet` is implemented like this:

```javascript
async _onDrop(event) {
    const data = TextEditor.getDragEventData(event);
    const allowed = Hooks.call("dropActorSheetData", this.actor, this, data);
    if (allowed === false) return;

    switch (data.type) {
        // Delegate to this._onDrop<TYPE> methods...
    }
}
```

To resolve this issue, the hook needs to be called by `ActorSheetSFRPG`. It's up in the air if it should also be called by `ActorSheetSFRPGStarship` and `ActorSheetSFRPGVehicle`.

**Comment by ian612** [comment]
This should now hopefully be properly resolved by #1493
