### ISSUE TITLE
Failure to open some sheets and add spells

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#764]
Some sheets are not able to open, and I'm also not able to add to the spellbook. Issues may be tied, as as least most of the sheets not opening I know have spells in them.

error when opening sheet

Error: One of original or other are not Objects!
[Detected 1 package: system:sfrpg]
    at mergeObject (commons.js:2359:13)
    at _mergeUpdate (commons.js:2416:14)
    at mergeObject (commons.js:2373:41)
    at _mergeUpdate (commons.js:2416:14)
    at mergeObject (commons.js:2373:41)
    at _mergeUpdate (commons.js:2416:14)
    at Object.mergeObject (commons.js:2373:41)
    at ActorSheetSFRPGCharacter._render (foundry.js:5063:19)
    at ActorSheetSFRPGCharacter._render (foundry.js:5780:17)
    at ActorSheetSFRPGCharacter._render (base.js:276:21)
    at ActorSheetSFRPGCharacter.render (foundry.js:5026:10)
    at ActorSheetSFRPGCharacter.render (foundry.js:6352:18)
    at ActorSheetSFRPGCharacter.render (base.js:272:22)
    at Token._onClickLeft2 (foundry.js:46921:16)
    at MouseInteractionManager.callback (foundry.js:27702:45)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:27916:17)
    at MouseInteractionManager._handleMouseDown (foundry.js:27878:66)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerDown (interaction.min.mjs:8:14214)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerDown (interaction.min.mjs:8:13543)

Error when creating spell in spellbook

Error: You are accessing the ItemSFRPG#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at ItemSFRPG._logV10CompatibilityWarning (commons.js:6617:14)
    at get data [as data] (commons.js:6517:24)
    at base.js:843:37
    at Array.reduce (<anonymous>)
    at ActorSheetSFRPGCharacter._prepareSpellbook (base.js:842:41)
    at ActorSheetSFRPGCharacter._prepareItems (character.js:125:32)
    at ActorSheetSFRPGCharacter.getData (base.js:153:14)
    at ActorSheetSFRPGCharacter.getData (character.js:31:33)
    at ActorSheetSFRPGCharacter._render (foundry.js:5067:29)
    at ActorSheetSFRPGCharacter._render (foundry.js:5780:17)
    at ActorSheetSFRPGCharacter._render (base.js:276:21)
    at ActorSheetSFRPGCharacter.render (foundry.js:5026:10)
    at ActorSheetSFRPGCharacter.render (foundry.js:6352:18)
    at ActorSheetSFRPGCharacter.render (base.js:272:22)
    at ActorSFRPG.render (foundry.js:13275:11)
    at ActorSFRPG.render (actor.js:116:22)
    at ActorSFRPG._onCreateEmbeddedDocuments (foundry.js:13428:10)
    at ActorSFRPG._onCreateEmbeddedDocuments (foundry.js:16618:11)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:12550:12)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12452:17)
    at async ItemSFRPG.createDocuments (commons.js:6085:23)
logCompatibilityWarning @ commons.js:1703
_logV10CompatibilityWarning @ commons.js:6617
get data @ commons.js:6517
(anonymous) @ base.js:843
_prepareSpellbook @ base.js:842
_prepareItems @ character.js:125
getData @ base.js:153
getData @ character.js:31
_render @ foundry.js:5067
_render @ foundry.js:5780
_render @ base.js:276
render @ foundry.js:5026
render @ foundry.js:6352
render @ base.js:272
render @ foundry.js:13275
render @ actor.js:116
_onCreateEmbeddedDocuments @ foundry.js:13428
_onCreateEmbeddedDocuments @ foundry.js:16618
_handleCreateEmbeddedDocuments @ foundry.js:12550
_createEmbeddedDocuments @ foundry.js:12452
await in _createEmbeddedDocuments (async)
create @ commons.js:6712
await in create (async)
createDocuments @ commons.js:6085
createEmbeddedDocuments @ commons.js:6303
createEmbeddedDocuments @ actor.js:171
_onItemCreate @ base.js:547
(anonymous) @ base.js:216
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
commons.js:6921 Foundry VTT | Created Item with id [tE9jC2I7bfc7dYid] in parent Actor [tPbtz8mjhpSuDYUT]
foundry.js:747 TypeError: Cannot read properties of undefined (reading 'mode')
[Detected 1 package: system:sfrpg]
    at base.js:845:48
    at Array.reduce (<anonymous>)
    at ActorSheetSFRPGCharacter._prepareSpellbook (base.js:842:41)
    at ActorSheetSFRPGCharacter._prepareItems (character.js:125:32)
    at ActorSheetSFRPGCharacter.getData (base.js:153:14)
    at ActorSheetSFRPGCharacter.getData (character.js:31:33)
    at ActorSheetSFRPGCharacter._render (foundry.js:5067:29)
    at ActorSheetSFRPGCharacter._render (foundry.js:5780:17)
    at ActorSheetSFRPGCharacter._render (base.js:276:21)
    at ActorSheetSFRPGCharacter.render (foundry.js:5026:10)
    at ActorSheetSFRPGCharacter.render (foundry.js:6352:18)
    at ActorSheetSFRPGCharacter.render (base.js:272:22)
    at ActorSFRPG.render (foundry.js:13275:11)
    at ActorSFRPG.render (actor.js:116:22)
    at ActorSFRPG._onCreateEmbeddedDocuments (foundry.js:13428:10)
    at ActorSFRPG._onCreateEmbeddedDocuments (foundry.js:16618:11)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:12550:12)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12452:17)
    at async ItemSFRPG.createDocuments (commons.js:6085:23)

**Comment by LebombJames** [comment]
This should now be fixed

**Comment by wildj79** [comment]
I haven't been able to reproduce this, but I'm also on a fairly fresh world with newish PC created specifically for testing. Could you export a couple of actors that this is happening to, zip them up and then attach them to this issue so I can use them to troubleshoot with?
