### ISSUE TITLE
Console Error in ActorItemHelper.migrateItems() after v9 to v10 migration

### ISSUE THREAD

**Issue by TheGreatRedDuke** [foundryvtt-starfinder/foundryvtt-starfinder#790]
Hi,

After migrating from Foundry vv.9.280 to v10 (build 288) I receive an error in console related to `ActorItemHelper.migrateItems()`. I've ensured I'm using the most up to date Starfinder version (v0.20.3) and have tested this running: no modules, some modules, and all my modules. In all cases the error is present and identical.

The error occurs when the world is initially loaded. I'm also not able to see any obvious issues when looking through my actors, but the error makes me nervous that something didn't correctly migrate and may come back to bite me later.

Please let me know if there's any other information I can provide.

```
Uncaught (in promise) ReferenceError: currentStorage is not defined                             actor-inventory-utils.js:971
[Detected 1 package: system:sfrpg]
    at ActorItemHelper.migrateItems (actor-inventory-utils.js:971:31)
    at migrateOldContainers (sfrpg.js:338:51)
    at Object.fn (sfrpg.js:321:13)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7909:11)
    at async Game._initializeGameView (foundry.js:8954:5)
    at async Game.initialize (foundry.js:7782:5)

migrateItems | @ | actor-inventory-utils.js:971
-- | -- | --
  | migrateOldContainers | @ | sfrpg.js:338
  | (anonymous) | @ | sfrpg.js:321
  | #call | @ | foundry.js:724
  | callAll | @ | foundry.js:681
  | setupGame | @ | foundry.js:7909
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:8954
  | _initializeView | @ | foundry.js:8930
  | initialize | @ | foundry.js:7782
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁libWrapperInit | @ | libWrapper-api.js:805
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @ | foundry.js:79087
```

**Comment by LebombJames** [comment]
This won't cause you any problems. A quick way to fix it is to re-add any container items you have from the compendium to your character sheet

**Comment by LebombJames** [comment]
There are still some issues with containers as per #779. The NaN issue is also known, and was an issue on V9. Don't worry about replacing containers if it didn't fix it, again, it won't break anything.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
